// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
    helloWorld: string;
    links: string;
    teams: string;
    welcome: string;
    welcomeImage: string;
}
const cssExports: CssExports;
export default cssExports;
